theme: jekyll-theme-slate
remote_theme: pages-themes/cayman@v0.2.0
title: Cornerstone Ambulatory Surgery Center LLC
description: Landing page directing patients and authorized requestors for medical records
plugin: jekyll-remote-theme

 # Conversion
 markdown            : kramdown
 highlighter         : rouge
 lsi                 : false
 excerpt_separator   : "\n\n"
 incremental         : false

 # Serving
 detach              : false
 port                : 4000
 host                : 127.0.0.1
 baseurl             : "" # does not include hostname
 show_dir_listing    : false

 # Outputting
 permalink           : date
 paginate_path       : /page:num
 timezone            : null

 quiet               : false
 verbose             : false
 defaults            : []

 liquid:
   error_mode        : warn
   strict_filters    : false
   strict_variables  : false

 # Markdown Processors
 kramdown:
   auto_ids          : true
   entity_output     : as_char
   toc_levels        : [1, 2, 3, 4, 5, 6]
   smart_quotes      : lsquo,rsquo,ldquo,rdquo
   input             : GFM
   hard_wrap         : false
   footnote_nr       : 1
   show_warnings     : false
